### ISSUE TITLE
Missing O_ACCMODE macro and wrong O_RDWR

### ISSUE THREAD

**Issue by fjtrujy** [ps2dev/ps2sdk#102]
Hello,

Taking a look at the `io_common.h`, we have:

```
#define O_RDONLY	0x0001
#define O_WRONLY	0x0002
#define O_RDWR		0x0003
#define O_DIROPEN	0x0008	// Internal use for dopen
#define O_NBLOCK	0x0010
#define O_APPEND	0x0100
#define O_CREAT		0x0200
#define O_TRUNC		0x0400
#define	O_EXCL		0x0800
#define O_NOWAIT	0x8000
```

Following this doc, https://www.gnu.org/software/libc/manual/html_node/Access-Modes.html we have:
```
Macro: int O_ACCMODE
This macro stands for a mask that can be bitwise-ANDed with the file status flag value to produce a value representing the file access mode. The mode will be O_RDONLY, O_WRONLY, or O_RDWR. (On GNU/Hurd systems it could also be zero, and it never includes the O_EXEC bit.)
```

So, it  would means that `O_ACCMODE` should be `O_RDONLY | O_WRONLY | O_RDWR`, however `O_RDWR` is already `O_RDONLY | O_WRONLY`

Should we modify some values here? I don't know if this could have additional issues, but can we have something like:
```
#define O_RDONLY	0x0001
#define O_WRONLY	0x0002
#define O_RDWR		0x0004
#define O_ACCMODE	0x0007
#define O_DIROPEN	0x0008	// Internal use for dopen
#define O_NBLOCK	0x0010
#define O_APPEND	0x0100
#define O_CREAT		0x0200
#define O_TRUNC		0x0400
#define	O_EXCL		0x0800
#define O_NOWAIT	0x8000
```

Thanks

**Comment by sp193** [comment]
O_RDWR is a convenience macro meant to represent O_RDONLY|O_WRONLY. This is a standard thing.

Sometimes you may also find that the IOP stuff are not always GNU or POSIX-compliant, but that is because we are Sony-compliant.

**Comment by fjtrujy** [comment]
Ok, in my case I suppose that the code that is trying to use `O_ACCMODE` I can make it works creating 
`#define O_ACCMODE O_RDWR`

Thanks.

Close the bug if you think that it doesn't make sense.

**Comment by sp193** [comment]
Yes, you can.
