### ISSUE TITLE
Deprecating the npmXXX callls

### ISSUE THREAD

**Issue by asmblur** [ps2dev/ps2sdk#103]
I'm the artist formerly known as Herben, one of the creators of Naplink.  The only truly valid reason to maintain Naplink related API calls is for cases where people wish to work on PS2link and have no other way to communicate with the console other than Naplink during that process.  I can't speak for my Napalm brethren but I, myself would be fine with deprecating anything Naplink specific.  Note that I say: deprecating, not all out removing.  As mentioned before, there still remain some use cases that necessitate having more than one method of communicating with the console while debugging another communication method(eg PS2link).  Until we have a reliable alternative to Naplink as a backup, I would highly recommend maintaining support for Naplink, along with preprocessor warnings to remind users that support will eventually end.
Just my $0.02

**Comment by TnA-Plastic** [comment]
Would makefile-flags in the makefile of a project (if someone chooses to use naplink) and a switch-case or call - if it should be build into or not be any feasible?

Why should it be depreciated anyway? Is there a specific issue (I suppose it doesn't work on the most recent SDK.)?

THX for all your contributions to the Scene! :)
Great that you and some other old-schoolers take a look here once in a while!

**Comment by asmblur** [comment]
Uhhh, I have no fucking clue why I wanted to deprecate it.Probably because I'd been planning to remake naplink but changed my mind.  Anyway, disregard this.  Just an old-schooler going senile. :D
