### ISSUE TITLE
Cannot find file "ps2.h"

### ISSUE THREAD

**Issue by bayan47** [ps2dev/ps2sdk#132]
I try build it from source, but when i build it compiler gets a fatal error in file ps2_dbg.c . Compiler cannot find a file with name — ps2.h . I can’t find it in source code too. Can you explain me,please, where i can find this file?

**Comment by rickgaiser** [comment]
What OS are you using?
Where did you get your toolchain from and how did you configure it?

Or even better, to get a working toolchain please follow these instructions:
https://github.com/ps2dev/ps2dev

**Comment by bayan47** [comment]
> What OS are you using?
> Where did you get your toolchain from and how did you configure it?
> 
> Or even better, to get a working toolchain please follow these instructions:
> https://github.com/ps2dev/ps2dev

Ok, i will try use this toolchain

**Comment by fjtrujy** [comment]
Hello @bayan47,
@rickgaiser is right you should try to install following the instructions of https://github.com/ps2dev/ps2dev

Please if you solved your problem, close this issue.

Thanks!
