### ISSUE TITLE
Request for tutorials, how-to's, IDE's/Engines and simple projects for start developing

### ISSUE THREAD

**Issue by terremoth** [ps2dev/ps2sdk#146]
I told on the on the ps2dev/ps2dev repo:

> There is a VERY HUGE LACK of tutorials and HOWTO's in the internet about how to develop even a simple "hello world" program/elf for PS2.  
> We need to change that too.  
> We also need Graphic/Programming Engines such as RenderWare for helping develop PS2 Homebrews. I saw someone created an open source reimplementation of renderware engine btw (https://github.com/aap/librw).

Can **this issue** be open for links, PDF's, docs, tutorials and projects links?

**Comment by fjtrujy** [comment]
I don't think that the proper way to share documentation and tutorials should be a "GitHub Issue".
It is a really bad idea. 
If you want to create tutorials, documentation and so on, we have a specific GitHub pages where you can put everything.

**Comment by terremoth** [comment]
Yes, good, ok them. We would need that in some moment.
