### ISSUE TITLE
Strange behavior in remove() and unlink()

### ISSUE THREAD

**Issue by jmgk77** [ps2dev/ps2sdk#157]
Hi,

I am having a strange behavior when deleting a file from memory card. I open, create files, read and write them, etc... But when i try to delete any file, the file is deleted **but a folder with same name is created** (!).

In my code:
```
    remove("mc0:BARULAND/08040336.PNG");
```
In PCSX2 log, i get:
```
    remove file mc0:BARULAND/08040336.PNG
    mkdir name mc0:BARULAND/08040336.PNG 
```
It happen both in a real PS2 and in PCSX2, both using unlink() and remove(), what make me believe is a problem in stdlib. I looked in ps2dev/libs/ps2sdk/iop/system/iomanx/src/iomanX.c, trying to find a missing `break` in a switch/case or the like, but found nothing.

Anybody had noticed anything similar?

**Comment by rickgaiser** [comment]
It's a known bug:
https://github.com/ps2dev/ps2sdk/blob/3c4e3ef0df01c49bdb4620c32d3496eeab5f7f81/ee/kernel/include/fileio.h#L64-L67

Use fileXio instead of fio.

NOTE: after calling fileXioInit() you will automatically use fileXio instead of fio for all read/write/remove/mkdir/.... functions.

**Comment by jmgk77** [comment]
Thanks for the quick reply!

I tried to include fileXio.h, but got:
```
error: #error "Using fio/fileXio functions directly in the newlib port will lead to problems."
```
I think i will try some workarounds in my code, and wait for the "official" fix

**Comment by KrahJohlito** [comment]
FYI: just in case you didn’t know, sbv_patch_fileio() fixes it for fio

**Comment by jmgk77** [comment]
Thanks very much!!
