### ISSUE TITLE
mcRead() gives me sceMcResDeniedPermit

### ISSUE THREAD

**Issue by faissaloo** [ps2dev/ps2sdk#168]
Whenever I try to read anything from a file I've successfully opened as read only with `mcOpen()` I always get -5 (sceMcResDeniedPermit). I'm not even quite sure what this error means let alone what causes it so I'd appreciate any pointers.

**Comment by TheAwesome98-Real** [comment]
What file are you trying to read?

**Comment by faissaloo** [comment]
I was basically going through every file and opening anything that wasn't a directory. Don't have the code anymore tho.

**Comment by sp193** [comment]
sceMcResDeniedPermit is defined in the Sony documentation, as an error which sceMcSync() returns when the memory card cannot be accessed; a PS memory card is inserted.

**Comment by faissaloo** [comment]
I hadn't opened the file before unless walking the directory or getting memory card info inadvertently opens the file or something weird like that. When I opened it I definitely opened it with read perms using `O_RDONLY` and it was a PS2 memory card.
Also I just realised that I actually still have the project, here's the zip: https://files.catbox.moe/rn47bc.zip

**Comment by sp193** [comment]
Was this built with Newlib? What's the value of O_RDONLY? Is it still 1?

**Comment by sp193** [comment]
Regarding your other comment in the code about why alignment doesn't work without the static keyword, it's because alignment on the stack (as a local variable) is impossible to guarantee.

**Comment by faissaloo** [comment]
@sp193 I don't really understand what Newlib is tbh, I just built it with the standard toolchain

**Comment by AKuHAK** [comment]
> @sp193 I don't really understand what Newlib is tbh, I just built it with the standard toolchain

Newlib was introduced in toolchain version 1.1, version 1.0 is the latest before that changes, however, I am not quite sure how newlib invention can affect that problem.

**Comment by sp193** [comment]
He passes O_RDONLY to sceMcOpen(). If this is not equal to 1 (it was equal to 1, with the classic libc), then this operation may not work.

**Comment by faissaloo** [comment]
> He passes O_RDONLY to sceMcOpen(). If this is not equal to 1 (it was equal to 1, with the classic libc), then this operation may not work.  

Yeah you're right, I just tried printing the O_RDONLY and it gives me 0

**Comment by fjtrujy** [comment]
Hello guys,
Sorry for the late reply.
@faissaloo I think that you're mixing things.

As you know we fully integrated `newlib` in the past, making our toolchain more portable and standard.
Here watching your code I see you're mixing concepts, for instance:
```c
mcOpen(0,0, currently_copying->fullpath, O_RDONLY);
```

You're using `mcOpen` which is a `NON POSIX` function, and using here the `O_RDONLY` flag.

If you want to use these specific `mcOpen, mcRead` functions you need to use the `IOP` specific flags for it.

However the main reason why we implemented `newlib` was to make the developer life easier, now you can use normal, `open`, `read` functions using the standard POSIX flags as `O_RDONLY`.

```c
#include <unistd.h>
#include <fcntl.h>
 
int main()
{
    int filedesc = open("mc0:/testfile.txt", O_WRONLY);
    if(filedesc < 0)
        return 1;
 
    return 0;
}
```

You can take a look to this file, to understand how it works.
https://github.com/ps2dev/ps2sdk/blob/master/ee/libc/src/ps2sdkapi.c

Thanks

**Comment by fjtrujy** [comment]
> Was this built with Newlib? What's the value of O_RDONLY? Is it still 1?
> If it's no longer 1, then that may be why.

Hello @sp193,
If you take a look to my previous response, I think that we was mixing internal ps2 functions for open/read/close file with POSIX flags from newlib.

Thanks

**Comment by sp193** [comment]
Yes. We may always have done that over the many years, so POSIX'fication of the PS2SDK just made this problem more visible. libmc in this project is an EE library.

The original documentation from Sony did not specify the standard flags, but it became the standard flags in the homebrew SDK.

**Comment by faissaloo** [comment]
@fjtrujy For this program I'd like to avoid using the POSIX functions since they're blocking and EE threads can't seem to use IO. What is the correct name for the flag I should be using/header I should be `#include`ing in order to open a file as read only?

**Comment by fjtrujy** [comment]
> @fjtrujy For this program I'd like to avoid using the POSIX functions since they're blocking and EE threads can't seem to use IO. Thanks I'll take a look at the ps2sdkapi file you linked.

As I said before here you can the conversion done (`IOP_O_RDONLY`):
https://github.com/ps2dev/ps2sdk/blob/master/ee/libc/src/ps2sdkapi.c#L218-L225

Thanks

**Comment by rickgaiser** [comment]
Perhaps we need to expose these in a header?
https://github.com/ps2dev/ps2sdk/blob/f5fc572873301873fce96ed78897ca93cdf5ba59/ee/libc/src/ps2sdkapi.c#L98-L107
So functions like mcOpen can be used with IOP flags.

Or we make it dummy proof, and convert the flags in mcOpen, just like we do in open? Then we don't have 2 sets of flags, and no confusion.
https://github.com/ps2dev/ps2sdk/blob/f5fc572873301873fce96ed78897ca93cdf5ba59/ee/libc/src/ps2sdkapi.c#L217-L225

I wasn't aware of other functions using these flags. Are there more functions like this on the EE that use IOP flags?

**Comment by sp193** [comment]
The only RPC libraries that use these flags are:
- fileio (fileXio and fileio in the homebrew SDK).
- libmc

Given that they were originally prefixed with "sce" and Sony never described them to be POSIX-compliant, I think giving them separate definitions from the standard POSIX flag bits is also a suitable approach.
Conversion is a possibility, but we may end up mixing the POSIX flags with non-standard Sony flags. For example, sceOpen() was designed to allow SCE_CdSTREAM to be passed, to open a file for streaming. It's a part of the original design, even if it's not used in the homebrew world.

**Comment by uyjulian** [comment]
This doesn't seem to be an issue anymore. Reopen if this is not the case
