### ISSUE TITLE
I'm newbie on PS2 SDK, please just one help to install it.

### ISSUE THREAD

**Issue by Special-Niewbie** [ps2dev/ps2sdk#186]
Hello everyone, I need to ask you one boring question for you :), but I'm new on PS2 SDK; so to install/prepare this SDK I need to download the main git source files and then into the main source folder to use `make` and `make install` ? Or this SDK to working I need to set in different way?

**Comment by TnA-Plastic** [comment]
You:
- source your profile
- install the dependencies
- clone the repo
- execute the install-script

**Comment by Special-Niewbie** [comment]
You:

THANKS :+1:
