### ISSUE TITLE
Edit "UI_Install.exe" to split files for a PS2 FAT32 USB HDD

### ISSUE THREAD

**Issue by BourgeoisDirk** [ps2dev/ps2sdk#248]
Note: not related, but looking for help.
I got "UI Install" (exe and cpp source) from  [https://sksapps.haldrie.com/ps2hd.php](https://sksapps.haldrie.com/ps2hd.php)
The only problem is, it appears to have a bug, it limits the filename length to 31 characters instead of 32.
OPL, OPLManager and USbUtil all work fine with 32 chars.

But i cannot for the life of me seem to be able to make a new build with editing the .cpp source file.
Neither do I have any luck disassembling it in the attempt to try and change "if (strlen((const char *)argv[3]) > 0x1F)" "0x1F" (31) into a 32. 

Help would be welcome

**Comment by BourgeoisDirk** [comment]
Nevermind, it seems if i force a 32 character game name (which is valid for OPL) that USBUtil falls flat on its face.
This because apparently the ul.cfg file has some dumb shit like this:
32 character name in ul.cfg seen as invalid: "Syphon Filter - The Omega Strainul.SCES_520.33        "
31 character name in ul.cfg seen as valid: "Syphon Filter - The Omega Strai ul.SCES_520.33        "

**Comment by sp193** [comment]
It looks like USBUtil expects it to be 32-characters long, inclusive of the NULL.
Being a piece of homebrew software that is also closed-source, USBExtreme's data format was reverse-engineered. So this sort of thing was bound to happen.
