### ISSUE TITLE
Can you help me please!

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [ps2dev/ps2sdk#256]
Hey yall, so anyways i was trying to compile one of the examples today, but when i type make into the Ubuntu terminal it gave me a error. The error says: mips64r5900el-ps2-elf-gcc -D_EE -G0 -O2 -Wall  -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ps2sdk/common/include -I.  -c main.c -o main.o
make: mips64r5900el-ps2-elf-gcc: No such file or directory
make: *** [/usr/local/ps2dev/ps2sdk/samples/Makefile.eeglobal:63: main.o] Error 127
idk what this means so can you help me please!

**Comment by Masamune3210** [comment]
It means it can't find that file, either your environment isn't set up correctly, you are missing a dependency, or you are in the wrong folder/similar issue

**Comment by PS-2Online** [comment]
I don't know what the problem is but whenever I ran make without root access, it gave me errors. But ever since I used sudo -i it began to work. I always run cd and the folder name of what I am about to make then simlly run make. Also, make sure you edited the bash rc file as you would bash profile.

**Comment by terremoth** [comment]
@NeoGeoFreak2004 Do you have all your ps2 environment vars setted?

![image](https://user-images.githubusercontent.com/11032344/182602262-02acc673-fe0d-4025-8514-020445426e3f.png)

(https://github.com/ps2dev/ps2dev)

**Comment by uyjulian** [comment]
PATH variable seems to be incorrect.

This doesn't seem to be an issue anymore. Reopen if this is not the case
