### ISSUE TITLE
Anyone have a keyboard input interpreter?

### ISSUE THREAD

**Issue by PS-2Online** [ps2dev/ps2sdk#316]
I would like to implement keyboards in my program to allow the user to name themselves, etc. Is there a library for keyboard input? Thanks and God bless.

**Comment by AKuHAK** [comment]
Github issues isnt the place for chatting and resolving your local problems. You can join our discord channel for such type of questions.
[![Discord](https://img.shields.io/discord/652861436992946216?style=flat&logo=Discord)](https://discord.gg/CVFUa9xh6B)
