### ISSUE TITLE
Issue with Dockerfile

### ISSUE THREAD

**Issue by andjnewb** [ps2dev/ps2sdk#320]
I'm not sure if this is intentional or not, but the docker file contains the ARG BASE_DOCKER_IMAGE but it is not assigned a value. I'm assuming this was meant to be ubuntu:latest or something similar. If anyone on the dev team could let me know what it should be, that would be much appreciated!

**Comment by fjtrujy** [comment]
The docker image you should use is `ps2dev/ps2dev:latest`, the one you’re trying to use is for internal development
