### ISSUE TITLE
`printf` not working fine with `fileXio`

### ISSUE THREAD

**Issue by fjtrujy** [ps2dev/ps2sdk#332]
When we use `fileXio` the `printf` messages stop working when running `PCSX2`.

When using `ps2client` is still working because the `udptty` driver is closing and opening again the `fd` `0` and `1`, as you can see here, for redirecting the output:
https://github.com/ps2dev/ps2sdk/blob/master/iop/network/udptty/src/udptty.c#L200-L208

I suppose that something similar should be done in `fileXio`.
Are the `printf` messages with `fileXio` working in `DevTool machines`? (@uyjulian could you double-check it)?

The example:

```c
int main(int argc, char **argv) {
  SifExecModuleBuffer(&iomanX_irx, size_iomanX_irx, 0, NULL, NULL);	
  SifExecModuleBuffer(&fileXio_irx, size_fileXio_irx, 0, NULL, NULL);
  fileXioInit();

  while(1) {
    printf("Hello world with fileXio drivers!\n");
  }
}
```

**Comment by uyjulian** [comment]
Last time I checked, `printf` messages with `fileXio` are working with DTL-T machines.  

Once I reverse the `STDIO` and `IOMAN` module, I'll probably have a better understanding of how this all integrates and how to resolve this.

**Comment by fjtrujy** [comment]
> Last time I checked, `printf` messages with `fileXio` are working with DTL-T machines.
> 
> Once I reverse the `STDIO` and `IOMAN` module, I'll probably have a better understanding of how this all integrates and how to resolve this.

Was it before or after the newlib integration, #161 ?

**Comment by uyjulian** [comment]
> > Last time I checked, `printf` messages with `fileXio` are working with DTL-T machines.
> > Once I reverse the `STDIO` and `IOMAN` module, I'll probably have a better understanding of how this all integrates and how to resolve this.
> 
> Was it before or after the newlib integration, #161 ?

After

**Comment by rickgaiser** [comment]
These printf messages that magically appear in PCSX2, do you know how they get there?

I'm assuming they are IOP SIO writes, not EE SIO? And I'm assuming ioman somehow uses fd=0 and fd=1 to write to the IOP serial port. Can you confirm the PCSX2 output you see is the IOP serial port output? And if not, do you know what it is?

Searching in the ps2sdk sources I can find no driver for using the iop serial port.
We could probably make an iop serial port driver (using ps1 code as example), then do the same thing we do with udptty:
https://github.com/ps2dev/ps2sdk/blob/56dc1922d50c9a302c426b25d36c46fdbf30fdc6/iop/network/udptty/src/udptty.c#L200-L208

**Comment by fjtrujy** [comment]
> These printf messages that magically appear in PCSX2, do you know how they get there?
> 
> I'm assuming they are IOP SIO writes, not EE SIO? And I'm assuming ioman somehow uses fd=0 and fd=1 to write to the IOP serial port. Can you confirm the PCSX2 output you see is the IOP serial port output? And if not, do you know what it is?
> 
> Searching in the ps2sdk sources I can find no driver for using the iop serial port. We could probably make an iop serial port driver (using ps1 code as example), then do the same thing we do with udptty:
> 
> https://github.com/ps2dev/ps2sdk/blob/56dc1922d50c9a302c426b25d36c46fdbf30fdc6/iop/network/udptty/src/udptty.c#L200-L208

Watching into the PCSX2 code I saw it print messages coming from `SIO_TXFIFO`

https://github.com/PCSX2/pcsx2/blob/master/pcsx2/HwWrite.cpp#L314

I think that somehow `fio` redirect to SIO Write

**Comment by uyjulian** [comment]
PCSX2 hooks IOMAN `write` and SYSMEM `Kprintf`.  

`write`: https://github.com/PCSX2/pcsx2/blob/e3eae7fbe83aad3952e3ed6a8e56fc016b51a9c3/pcsx2/IopBios.cpp#L725  
`Kprintf`: https://github.com/PCSX2/pcsx2/blob/e3eae7fbe83aad3952e3ed6a8e56fc016b51a9c3/pcsx2/IopBios.cpp#L752

**Comment by fjtrujy** [comment]
In the end, it wasn't an issue in the `ps2sdk` it was `PCSX2` that wasn't hooking properly `fileXio`.
This PR https://github.com/PCSX2/pcsx2/pull/7007 has fixed the issue.

Cheers
