### ISSUE TITLE
Some kernel headers are not installed

### ISSUE THREAD

**Issue by tallero** [ps2dev/ps2sdk#389]
The README says the source distribution is different from the binary distribution of the SDK, so I suppose  it does imply a binary distribution does not copy all headers.

Is there a single command to install all the headers, too?

I'm asking because `gskit` asks for headers from the `kernel` SDK subproject.

**Comment by F0bes** [comment]
All of the headers that you would need is provided in the binary distribution.
If you're using a makefile, make sure you follow the proper layout as located in the samples. It will automatically compile your object with the required include dirs.
If you're using a cmakelist, make sure you `set(CMAKE_TOOLCHAIN_FILE $ENV{PS2SDK}/ps2dev.cmake)` **before** your `project()`

To verify that your binary distribution is correct, you can check `$PS2SDK/ee/include` and see if kernel.h is located there.

**Comment by uyjulian** [comment]
Feel free to reopen if this is still an issue
