### ISSUE TITLE
`HDDLOAD.IRX`: is there any open source implementation around?

### ISSUE THREAD

**Issue by israpps** [ps2dev/ps2sdk#413]
I can't find any information on this IRX.

all I know is that it's needed for loading HDD MBR program on PCMCIA or 70k PS2s.

I already asked @sp193 if he could disclose his implementation (see FreeMcBoot installer package) but he didn't answer my emails.

if there aren't any open source options around. could someone link me to reliable information for reversing an IRX? i couldnt find any useful thing, only an ancient ghidra plugin that makes ghidra crash when I import a file into the project.

**Comment by sp193** [comment]
Hi.
Apologies for not responding. As mentioned, I have burnout and it is very difficult for me to do anything more about the PlayStation 2.
it's very ironic, but I needed to dig up my website's address. I had the source code available here: https://sites.google.com/view/ysai187/home/projects/initializing-the-ps2psx

As sent to you via e-mail:
If you don't mind my hddload.irx, you can take the copy from FMCB 1.966 and re-bundle it. The code for that hddload.irx is stable, as there is only 1 good way to load the update. If I remember right, earlier versions of 1.9x had a plain IRX, but I eventually changed them to KIRX so I could just use sceSifLoadModuleEncrypted() without any additional tricks.

You can use my system driver update KELF files, osdsys.elf, osd110.elf and osd130.elf. Unlike the Sony system driver, I only put small patches in these locations, which just update the EE kernel's ExecPS2() and some brower config syscalls, and update the OSDSYS's update path to mc:/BIEXEC-SYSTEM/osdmain.elf. Once run, the OSDSYS will be reloaded, and it will cause the SCPH-10000, SCPH-15000 and SCPH-18000 to attempt to load mc:/BIEXEC-SYSTEM/osdmain.elf.
In contrast, Sony had a small patch as osdsys.elf for the early SCPH-10000, which also changed the path to reference the osd110.elf. On the other hand, osd110.elf, osd130.elf and osdmain.elf were identical HDD OSD browser programs, from what I remember.

**Comment by sp193** [comment]
For reverse-engineering, I used ps2dis. It hasn't been developed since the early 2000s or something, but I found it easy to use.

Please note that the modules you find on the memory card from Sony, are likely KIRX/KELF and are not plaintext ELF/IRX. Despite their file extensions.

**Comment by israpps** [comment]
> Hi. Apologies for not responding. As mentioned, I have burnout and it is very difficult for me to do anything more about the PlayStation 2. it's very ironic, but I needed to dig up my website's address. I had the source code available here: https://sites.google.com/view/ysai187/home/projects/initializing-the-ps2psx
> 
> As sent to you via e-mail: If you don't mind my hddload.irx, you can take the copy from FMCB 1.966 and re-bundle it. The code for that hddload.irx is stable, as there is only 1 good way to load the update. If I remember right, earlier versions of 1.9x had a plain IRX, but I eventually changed them to KIRX so I could just use sceSifLoadModuleEncrypted() without any additional tricks.
> 
> You can use my system driver update KELF files, osdsys.elf, osd110.elf and osd130.elf. Unlike the Sony system driver, I only put small patches in these locations, which just update the EE kernel's ExecPS2() and some brower config syscalls, and update the OSDSYS's update path to mc:/BIEXEC-SYSTEM/osdmain.elf. Once run, the OSDSYS will be reloaded, and it will cause the SCPH-10000, SCPH-15000 and SCPH-18000 to attempt to load mc:/BIEXEC-SYSTEM/osdmain.elf. In contrast, Sony had a small patch as osdsys.elf for the early SCPH-10000, which also changed the path to reference the osd110.elf. On the other hand, osd110.elf, osd130.elf and osdmain.elf were identical HDD OSD browser programs, from what I remember.

Thanks for answering!

Your website was the first place I checked for information...

However, no HDDLOAD (nor MBR.KELF) source are available there.

With the help of ghidra I've learnt that HDDLOAD expects four arguments:
```
-stat 0x0010000 -osd ???
```
where `???` is generated by a `sprintf(a, "%p", some_variable_from_stack);` I still haven't figured out the value

Also, I know that when HDDLOAD finished it's job I simply do `execps2(0x0010000, NULL, argv, argv);` where argv contains `rom0:HDDBOOT` at least

**Comment by uyjulian** [comment]
> > Hi. Apologies for not responding. As mentioned, I have burnout and it is very difficult for me to do anything more about the PlayStation 2. it's very ironic, but I needed to dig up my website's address. I had the source code available here: https://sites.google.com/view/ysai187/home/projects/initializing-the-ps2psx
> > As sent to you via e-mail: If you don't mind my hddload.irx, you can take the copy from FMCB 1.966 and re-bundle it. The code for that hddload.irx is stable, as there is only 1 good way to load the update. If I remember right, earlier versions of 1.9x had a plain IRX, but I eventually changed them to KIRX so I could just use sceSifLoadModuleEncrypted() without any additional tricks.
> > You can use my system driver update KELF files, osdsys.elf, osd110.elf and osd130.elf. Unlike the Sony system driver, I only put small patches in these locations, which just update the EE kernel's ExecPS2() and some brower config syscalls, and update the OSDSYS's update path to mc:/BIEXEC-SYSTEM/osdmain.elf. Once run, the OSDSYS will be reloaded, and it will cause the SCPH-10000, SCPH-15000 and SCPH-18000 to attempt to load mc:/BIEXEC-SYSTEM/osdmain.elf. In contrast, Sony had a small patch as osdsys.elf for the early SCPH-10000, which also changed the path to reference the osd110.elf. On the other hand, osd110.elf, osd130.elf and osdmain.elf were identical HDD OSD browser programs, from what I remember.
> 
> Thanks for answering!
> 
> Your website was the first place I checked for information...
> 
> However, no HDDLOAD (nor MBR.KELF) source are available there.
> 
> With the help of ghidra I've learnt that HDDLOAD expects four arguments:
> 
> ```
> -stat 0x0010000 -osd ???
> ```
> 
> where `???` is generated by a `sprintf(a, "%p", some_variable_from_stack);` I still haven't figured out the value
> 
> Also, I know that when HDDLOAD finished it's job I simply do `execps2(0x0010000, NULL, argv, argv);` where argv contains `rom0:HDDBOOT` at least

Yes, there is no source.

**Comment by sp193** [comment]
I didn't realize I missed this module. Thanks for bringing that up.
I have added the code and some relavent bits from the main part of FMCB, as well as the FMCB Installer.
I also found that the MBR sample's link wasn't the correct one, and has been wrong since 2019.

**Comment by sp193** [comment]
The invocation is actually something like this:
```
			strcpy(CmdStr, "-osd");
			strcpy(&CmdStr[5], "0x00100000");
			strcpy(&CmdStr[16], "-stat");
			sprintf(&CmdStr[22], "%p", HDDLoadStatArea);
			CmdStr[sizeof(CmdStr)-1]='\0';

			sprintf(ModulePath, "mc%u:/%s/hddload.irx", device, SysExecFolder);
			SifLoadModule(ModulePath, sizeof(CmdStr), CmdStr);
```

Whereby "osd" specifies where to load the HDD OSD update, while "stat" is an aligned memory location that will receive the outcome of the loading process. It must be aligned to a 16-byte boundary and is 16 bytes long, as this will be updated with DMA.

**Comment by sp193** [comment]
I think it was the other way around. Looks like I last used plain IRX modules. So it must have been a KIRX in the early FMCB 1.9x versions. Then this would be even better, I suppose.

**Comment by israpps** [comment]
THANK YOU SO MUCH!!!!

**Comment by sp193** [comment]
Loading HDDLOAD will cause the HDD to be spun up, before the program is located and loaded to the given address. The outcome is sent to the memory address specified by the "-stat" argument. If successfully loaded, the OSD is loaded to the address specified by "-osd".

As mentioned in the new package, Sony renders the "Sony Computer Entertainment" screen as HDDLOAD is running, and loading HDDLOAD with SifLoadModule etc is a blocking process. So you might want to do something similar, else the user will be shown a black screen...

Note that the system configuration can specify whether:

1. The ATA interface is disabled (enabled by default).
2. HDD booting is disabled (disabled by default).

HDD booting being disabled, means that the HDD will be shut down regardless of whether an OSD was successfully loaded from the HDD.
So when you install/set up your software, you should use the libcdvd config functions to unset bit 1 and set bit 2, as described.

**Comment by sp193** [comment]
By the way, do consider offering a method to power off the PS2. I added this feature later on, to give FMCB a way to power off the HDD unit (and/or connected USB HDD) nicely. You probably should shut down the HDD unit properly from here, and also from the power-off callback.

The expansion-bay units can feedback to the program that the user pressed the power button, but this cannot be done with the SCPH-10000, SCPH-15000 (not sure about the SCPH-18000, but it's possibly a missing feature there too), and likely the SCPH-700xx.

I think it's more acceptable for 3.5" HDDs, but just cutting power to a 2.5" HDD is usually considered an emergency shutdown. And by documentation, most HDDs are rated for far less of these cycles than the normal ones.

```
	fileXioUmount("pfs0:");
	/* Close all files */
	fileXioDevctl("pfs:", PDIOC_CLOSEALL, NULL, 0, NULL, 0);
	/* Switch off DEV9 */
	fileXioDevctl("dev9x:", DDIOC_OFF, NULL, 0, NULL, 0);

	// As required by some (typically 2.5") HDDs, issue the SCSI STOP UNIT command to avoid causing an emergency park.
	fileXioDevctl("mass0:", USBMASS_DEVCTL_STOP_UNIT, NULL, 0, NULL, 0);
```

DDIOC_OFF will cause the dev9 module to invoke all callbacks. Our homebrew ATAD module will issue the STANDBY IMMEDIATE to shut down the HDD, unlike the Sony version.

Similarly, I added this devctl() call to USBHDFSD, to achieve a similar effect with the SCSI STOP UNIT command.

**Comment by sp193** [comment]
I have added a link to the FSCK program's source code. I appear to have uploaded it in 2016, but I see no mention of it on the page. So I have added link.

The MBR program would boot the FSCK program, if there is an issue with the disk.

**Comment by israpps** [comment]
> Loading HDDLOAD will cause the HDD to be spun up, before the program is located and loaded to the given address. The outcome is sent to the memory address specified by the "-stat" argument. If successfully loaded, the OSD is loaded to the address specified by "-osd".
> 
> As mentioned in the new package, Sony renders the "Sony Computer Entertainment" screen as HDDLOAD is running, and loading HDDLOAD with SifLoadModule etc is a blocking process. So you might want to do something similar, else the user will be shown a black screen...
> 
> Note that the system configuration can specify whether:
> 
> 1. The ATA interface is disabled (enabled by default).
> 2. HDD booting is disabled (disabled by default).
> 
> HDD booting being disabled, means that the HDD will be shut down regardless of whether an OSD was successfully loaded from the HDD. So when you install/set up your software, you should use the libcdvd config functions to unset bit 1 and set bit 2, as described.

How can I render the SCE intro?

**Comment by sp193** [comment]
You need to learn how to do 3D programming?

**Comment by israpps** [comment]
> You need to learn how to do 3D programming?

nono...

I mean, is there a way of triggering it from somewhere else than freemcboot?

Just like how krHACKen private bootloader shows the PSX splash screen

**Comment by sp193** [comment]
No, it is part of the OSDSYS program itself.

FMCB allows that boot animation to play by becoming part of the OSDSYS program during boot.

**Comment by israpps** [comment]
Will commit HDDLOAD source to PS2SDK soon (marking sp193 as author ofc)
