### ISSUE TITLE
i got ths error

### ISSUE THREAD

**Issue by alimadhi** [ps2dev/ps2sdk#42]
-smb_cdvdman
 -hdd_cdvdman
 -hdd_hdpro_cdvdman
 -cdvdfsv
 -in-game SMSTCPIP
 -in-game SMAP
 -smbinit
 -ps2fs
 -usbhdfsd
 -usbhdfsdfsv
 -ps2atad
ps2atad.c: In function `ata_device_set_transfer_mode':
ps2atad.c:748: `ATAD_XFER_MODE_MDMA' undeclared (first use in this function)
ps2atad.c:748: (Each undeclared identifier is reported only once
ps2atad.c:748: for each function it appears in.)
ps2atad.c:751: `ATAD_XFER_MODE_UDMA' undeclared (first use in this function)
ps2atad.c:754: `ATAD_XFER_MODE_PIO' undeclared (first use in this function)
ps2atad.c: In function `ata_init_devices':
ps2atad.c:974: `ATAD_XFER_MODE_UDMA' undeclared (first use in this function)
make[2]: *** [ps2atad.o] Error 1
make[1]: *** [modules/hdd/atad/ps2atad.irx] Error 2
make: *** [all] Error 2

ali@W8 ~/open-ps2-loader
$

**Comment by sp193** [comment]
This is an OPL problem, not a PS2SDK issue. While I removed that definition from atad.h, those values originally could never be used by any program. I will make a pull request for OPL.

**Comment by alimadhi** [comment]
now this show after your changes

`
 -ps2atad
In file included from ps2atad.c:27:
../common/atad.h:81:24: warning: no newline at end of file
 -hdpro_atad
 -ps2hdd
In file included from hdd_fio.c:15:
../common/atad.h:81:24: warning: no newline at end of file
In file included from hdd.c:15:
../common/atad.h:81:24: warning: no newline at end of file
In file included from irx_imports.h:20,
                 from build-imports.c:1:
../common/atad.h:81:24: warning: no newline at end of file
In file included from ../libapa/src/apa.c:17:
../common/atad.h:81:24: warning: no newline at end of file
In file included from ../libapa/src/journal.c:15:
../common/atad.h:81:24: warning: no newline at end of file
In file included from ../libapa/src/free.c:17:
../common/atad.h:81:24: warning: no newline at end of file
In file included from ../libapa/src/password.c:15:
../common/atad.h:81:24: warning: no newline at end of file
 -genvmc
 -hdldsvr
 -ps2dev9
 -SMSUTILS
 -isofs
 -nbns
 -httpclient
Stripping...
Compressing...

ali@W8 ~/open-ps2-loader`

**Comment by sp193** [comment]
I didn't remove the line from atad.h, so it was always missing. Those aren't actually errors, but warnings. If you do not like to see those warnings (which don't affect the build), you can just open modules/hdd/common/atad.h and add a newline at the bottom of it.

**Comment by Jay-Jay-OPL** [comment]
Just wanted to share that I don't see those warnings when compiling OPL.  But then again, I am using an older version of PS2SDK:

My last update version:
`commit e825d3b47fe0df8acf86a47dba052ad235f92e09
Author: sp193
Date:   Mon Jan 30 17:12:02 2017 +0800`

Perhaps something in the new changes in PS2SDK or other PS2DEV utilities is detecting and triggering those warnings?

**Comment by sp193** [comment]
I don't see it either, but it is definitely a feature of GCC. If there is a difference in behaviour here, it may be due to how he is checking out his files (i.e. the final newline character is getting lost).

**Comment by alimadhi** [comment]
what is the line to added ? please can you write it to me ?
