### ISSUE TITLE
Option argument for sceUsbdTransferPipe()?

### ISSUE THREAD

**Issue by Tatsh** [ps2dev/ps2sdk#424]
I am disassembling some code and it seems like the `void *option` argument in `sceUsbdTransferPipe` is actually a ` char[2]` (or `u8[2]`) and maybe it contains transfer direction and request? It is never called with more than 2 values in the code I am examining.

Values I've seen being passed in:

- `NULL`
- `{0x80, 6}`
- `{33, 9}`
- `int v12 = 0x80` passing `&v12`, same as `(int *)0x80`
- `int v12 = 1` passing `&v12`, same as `(int *)1`
- `{0, 9}`

So I've deduced some of these to various constants in usbd.h. `0x80` would be `USB_DIR_IN` and `0` would mean `USB_DIR_OUT`. `9` in the second field maybe is `USB_REQ_SET_REPORT`? I do not know what value `33` means however in the first field.

Also does anyone know what the value `0` means when `sceUsbdScanStaticDescriptor` is called like so: `sceUsbdScanStaticDescriptor(devId, configDescriptorPtr, 0)`? It is not defined in the constants.

**Comment by rickgaiser** [comment]
Have you seen this code in ps2sdk?

https://github.com/ps2dev/ps2sdk/blob/325ad9462f98f514496d78ef7bd525f8fae24b21/iop/usb/usbd/include/usbd_macro.h#L21-L40

I'm assuming you don't have the sony SDK documents. The info you're looking for is in "PS2_IOP-Reference-Device-3.0.2.pdf":
![image](https://user-images.githubusercontent.com/4712159/233318294-06c16ad8-3a6d-491e-992c-88f0a83e2863.png)

Type:
![image](https://user-images.githubusercontent.com/4712159/233318841-bdaea178-e82f-493a-9738-bfaa43013b7e.png)

**Comment by Tatsh** [comment]
Thanks. That solves it for me.
