### ISSUE TITLE
MIPTBP1 and 2 incorrect bitmask

### ISSUE THREAD

**Issue by crypt4489** [ps2dev/ps2sdk#460]
In common/include/gs_gp.h, MIPTBP1 and 2 have an incorrect bitmask for the addresses of the mip levels. It should mask the lower 14 bits not 10 bits as it does now.

**Comment by rickgaiser** [comment]
https://github.com/ps2dev/ps2sdk/blob/a8e58fdeea62efb4ee803e3bc2c89ab8bc0305e2/common/include/gs_gp.h#L223-L231

You're right, can you make a PR for changing this?

**Comment by crypt4489** [comment]
@rickgaiser see #461
