### ISSUE TITLE
[PROPOSAL]: dispatch IRX modules built by debug PS2SDK into the release section

### ISSUE THREAD

**Issue by israpps** [ps2dev/ps2sdk#506]
just what the title says.
This would save time, since CI could just `wget` that file and unpack the desired IRX instead of doing
```sh
git clone https://github.com/ps2dev/ps2sdk
cd ps2sdk
make clean debug install
```

**Comment by fjtrujy** [comment]
What we can do is actually release both versions, for instance `fileXio.irx` and `fileXio_debug.irx` in this way you safely use one or the other given your makefile config

**Comment by israpps** [comment]
> What we can do is actually release both versions, for instance `fileXio.irx` and `fileXio_debug.irx` in this way you safely use one or the other given your makefile config

Another option would be to compile separately the debug builds and toss them at
```
$PS2SDK/iop/irx_debug/
```

Another option would be to add a recipe to PS2SDK makefile that only builds IRX
