### ISSUE TITLE
Issue with `sleep` function

### ISSUE THREAD

**Issue by fjtrujy** [ps2dev/ps2sdk#527]
## Description
`sleep` functions look to be inaccurate from time to time.

Following the next example:
```c
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>  // For sleep function

// Function to calculate the time difference between two timespec structures
struct timespec timespec_diff(struct timespec start, struct timespec end) {
    struct timespec temp;
    if ((end.tv_nsec - start.tv_nsec) < 0) {
        temp.tv_sec = end.tv_sec - start.tv_sec - 1;
        temp.tv_nsec = 1000000000 + end.tv_nsec - start.tv_nsec;
    } else {
        temp.tv_sec = end.tv_sec - start.tv_sec;
        temp.tv_nsec = end.tv_nsec - start.tv_nsec;
    }
    return temp;
}

int main() {
    // I want to create a program that uses 100 times usleep function with values between 7500 and 12000
    // then check if the sleep function is working properly comparing times before and after the sleep function
    // and then print the difference between the times
    struct timespec start, end, timeDifference;
    int random, got, diff, biggerDiff, biggerRandom, biggerGot;
    biggerDiff = 0;
    for (int i = 0; i < 10000; i++) {
        random = rand() % 4500 + 7500;
        clock_gettime(CLOCK_MONOTONIC, &start);
        usleep(random);
        clock_gettime(CLOCK_MONOTONIC, &end);
        
        timeDifference = timespec_diff(start, end);
        got = (timeDifference.tv_sec * 1000000000 + timeDifference.tv_nsec) / 1000;
        diff = abs(abs(random) - abs(got));
        if (diff > biggerDiff) {
            biggerDiff = diff;
            biggerRandom = random;
            biggerGot = got;
        }
        printf("Requested %d: got %d ==> diff: %d\n", random, got, diff);
    }

    printf("Bigger diff: %d, requested: %d, got: %d\n", biggerDiff, biggerRandom, biggerGot);
    SleepThread();
    
    return 0;
}
```

I would expect `diff` to be minimal something around `20 usecs` max, and it looks to be the majority of the cases, but from time to time it generates bigger values:
```
Requested 8108: got 8123 ==> diff: 15
Requested 10466: got 10478 ==> diff: 12
Requested 9985: got 10000 ==> diff: 15
Requested 10652: got 10665 ==> diff: 13
Requested 11383: got 11392 ==> diff: 9
Requested 7741: got 7750 ==> diff: 9
Requested 11934: got 11949 ==> diff: 15
Requested 9464: got 9478 ==> diff: 14
Requested 11404: got 11415 ==> diff: 11
Requested 8681: got 8691 ==> diff: 10
Requested 10863: got 10870 ==> diff: 7
Requested 11186: got 11399 ==> diff: 213
Requested 8977: got 8987 ==> diff: 10
Requested 7860: got 7873 ==> diff: 13
Requested 10768: got 10779 ==> diff: 11
Requested 8069: got 8078 ==> diff: 9
Requested 9851: got 9863 ==> diff: 12
Requested 9154: got 9164 ==> diff: 10
Requested 11683: got 11698 ==> diff: 15
```

And then the bigger diff:
```
Bigger diff: 113796, requested: 10661, got: 124457
```
That means something is wrong almost 114 ms of diff.

Cheers.

**Comment by fjtrujy** [comment]
Ping @davidgfnet and @uyjulian to be the most experts on this area

**Comment by fjtrujy** [comment]
I have tried reverting https://github.com/ps2dev/ps2sdk/pull/470/commits and it looks to works fine, so it must be an issue introduced there:
```
Bigger diff: 22, requested: 10395, got: 10417
```

**Comment by uyjulian** [comment]
nanosleep says <https://man7.org/linux/man-pages/man2/nanosleep.2.html> 
> nanosleep() suspends the execution of the calling thread until either **at least** the time specified in `*req` has elapsed

So this would be conformant behavior either way, but more accuracy is better

**Comment by irixxxx** [comment]
> nanosleep says https://man7.org/linux/man-pages/man2/nanosleep.2.html
> 
> > nanosleep() suspends the execution of the calling thread until either **at least** the time specified in `*req` has elapsed
> 
> So this would be conformant behavior either way, but more accuracy is better

While being technically correct I have never seen anything like this in any Posix compatible system under low load. I don't have the proceedings anymore, but I think this provision was added to cover for systems under load where a timely scheduling after the timer expires isn't guaranteed.

**Comment by davidgfnet** [comment]
Seems like a regression to me.
Just for sanity checking it would be great to validate that clock_gettime is not returning garbage every now and then (it likely won't but better safe than sorry!)

**Comment by fjtrujy** [comment]
> Seems like a regression to me. Just for sanity checking it would be great to validate that clock_gettime is not returning garbage every now and then (it likely won't but better safe than sorry!)

I have specifically checked that, and it looks to works fine, as I did a similar example, this time instead of putting a `usleep` in the middle, I put a function to generate the first X prime numbers, and the values looks to be right too.

**Comment by irixxxx** [comment]
I inspected the code and I think it might be a race condition in the timer overflow handling.  That ApplyOverflow and its being called several times in the timer irq looks suspicious to me.
