### ISSUE TITLE
sceCdRM freezes when ELF was loaded by certain applications 

### ISSUE THREAD

**Issue by israpps** [ps2dev/ps2sdk#563]
[`sceCdRM`](https://github.com/search?q=repo%3Aps2dev%2Fps2sdk%20sceCdRM&type=code) freezes when the application calling it was executed by memory card annihilator or some ancient wLaunchELF versions (like the one bundled on Freedvdboot)

Is this a known issue? Is there any way to avoid this? Maybe I forgot to cleanup something. The issue happens even if an IOP reboot is performed. With homebrew cdfs IRX

**Comment by israpps** [comment]
> Not sure why do you need support inside ancient apps but you can use sceCdAltRM https://github.com/ps2homebrew/PS2Ident/blob/9032110d1baac90987e8c61e8582f249c4766e08/libcdvd_add.c#L103

Because if KELFBinder detects FreeMcBoot multi install it tells the user to format card before installing update. And the most used app for formatting is MCA.

Also, wLaunchELF from Freedvdboot has the issue, so users trying to install PS2BBL from a Freedvdboot disc will also have this issue

**Comment by AKuHAK** [comment]
So, does sceCdAltRm works? Or fail the same way?

**Comment by israpps** [comment]
> So, does sceCdAltRm works? Or fail the same way?

Haven't tested yet. Will report back as soon as I can

**Comment by israpps** [comment]
Seems like I found the issue, cdvd RPC was not beein initialized.

What should I do @AKuHAK? close this issue or rename it to "sceCdRM sometimes work without RPC Init" 😆
