### ISSUE TITLE
![Uploading IMG_8684.jpeg…]()

### ISSUE THREAD

**Issue by elenrozh** [ps2dev/ps2sdk#574]
![Uploading IMG_8684.jpeg…]()

_Originally posted by @elenrozh in https://github.com/ps2dev/ps2sdk/issues/499#issuecomment-2018512367_

**Comment by fjtrujy** [comment]
What kind of issue is this?

**Comment by israpps** [comment]
> What kind of issue is this?

He tried to upload a screenshot to the issue title...
