### ISSUE TITLE
[System 2x6] default behaviour of `_libcglue_init()` causes system 2x6 to freeze before reaching `main()`

### ISSUE THREAD

**Issue by israpps** [ps2dev/ps2sdk#601]
adding this fixed the issue
```c
   void _libcglue_init() {}
   void _libcglue_deinit() {}
```

however, some apps may depend on whatever is inside them.

I will take a closer look when I have time

I have only tested this on emulator. but I guess real COH-H's will have same issue

**Comment by israpps** [comment]
Found one issue after reading some parts of libcglue.

the issue is calling [`ps2time()`](https://github.com/ps2dev/ps2sdk/blob/master/ee/rpc/cdvd/src/scmd.c#L150-L193)
Wich inside has a call to CDVD RPC [`sceCdReadClock`](https://github.com/ps2dev/ps2sdk/blob/master/ee/rpc/cdvd/src/scmd.c#L120)

Namco arcades don't have CDVDFSV listed on `rom0:IOPBTCONF` [^ARCADE_IOPBTCONF]

Therefore, the most sane solution would be to override it like I did, but then call a custom implementation of it taking place after loading the IOPRP image and manually loading CDVDFSV:
```c
id = SifLoadStartModule("rom0:CDVDFSV", 0, NULL, &ret);
if (id < 0 || ret == 1) we_have_a_problem();
```

Another option would be to include a custom `IOPBTCONF` with the following contents into the already needed IOPRP Image:
```py
!include IOPBTCONF
CDVDFSV
```

****

[^ARCADE_IOPBTCONF]:
#### Arcade `IOPBTCONF`

```py
@800
SYSMEM
LOADCORE
BOARDINF
EXCEPMAN
INTRMANP
INTRMANI
SSBUSC
DMACMAN
TIMEMANP
TIMEMANI
SYSCLIB
HEAPLIB
EECONF
THREADMAN
VBLANK
IOMAN
MODLOAD
ROMDRV
STDIO
SIFMAN
#DECI2
#DECI2DRP
#DECI2DRS
#DECI2FILE
#DECI2HSYN
#DECI2KPRT
IGREETING
SIFCMD
REBOOT
LOADFILE
#APPLOAD
#DECI2LOAD
ACDEV
SIFINIT
FILEIO
CDVDMAN
SECRMAN
#SSND
#LED
EESYNC
```

**Comment by israpps** [comment]
Another option would be to change how we deal with RPC bindings on PS2SDK.

On KELFBinder, I made SECRSIF RPC Bind function return an error after any RPC bind failed 500 times.

Many apps Could benefit of such feature. of course, probably the app will not be able to function completely without that RPC. but at least it gives you a chance to call a function where you change the BG color to indicate and error, and if the lack of that RPC is severe, maybe call `SleepThread()`

**Comment by fjtrujy** [comment]
Hello @israpps !
Nice investigation.
I think that solution for you is actually easier than this...

On the file `ee/libcglue/src/rtc.c` we have that function `void _libcglue_rtc_update()` is weak, and this function is the only one that uses `ps2time`, so for your `[System 2x6]` machines you just need to do `void _libcglue_rtc_update() {}` and should be enough.

This function in theory is just used to get current date and time, so for https://man7.org/linux/man-pages/man2/gettimeofday.2.html , so unless you wanted to print the current date.... this shouldn't be a problem for you 😃 

If you see in the `ps2sdk` samples we have one which actually overrides this too, take a look at `ee/libcglue/samples/mem_test/main.c`.

Cheers

**Comment by fjtrujy** [comment]
@israpps any update?

**Comment by israpps** [comment]
> @israpps any update?

Haven't taken a look at it yet.

**Comment by uyjulian** [comment]
`cdvdfsv` is not loaded by default on those systems, but `fileio` `devctls` to get time to `cdrom:` should work since those systems have a newer `cdvdman`.

I'll eventually implement it once I make some improvements to ioman/iomanX/fileio differing version handling.
