### ISSUE TITLE
Issues compiling the ps2 port of SM64 and the new releases of OPL with the latest release of PS2DEV

### ISSUE THREAD

**Issue by wolfmanvid01** [ps2dev/ps2sdk#622]
The issues i got with SM64 are posted [here](https://github.com/fgsfdsfgs/sm64-port/issues/95), issues that had to do with typing confusions of the compiler

and the issues with OPL are [here](https://github.com/ps2homebrew/Open-PS2-Loader/issues/1238), having issues with typing problems, and linking some functions

**Comment by fgsfdsfgs** [comment]
This is really not the fault of PS2SDK but the result of the new version of GCC promoting some warnings to errors.

**Comment by fjtrujy** [comment]
Closing this issue as it has been solved.
It was new GCC 14 requirements.
