### ISSUE TITLE
mpfr-static

### ISSUE THREAD

**Issue by 564K** [ps2dev/ps2sdk#667]
Hello,
I tried to install ps2-sdk on archlinux using the package on the AUR but I saw that the package mpfr-static was needed and I was not able to installed it I gues that error message
>yay -S ps2-sdk
> -> No AUR package found for mpfr=4.2.0.p9
> -> mips64r5900el-ps2-elf-gccmips64r5900el-ps2-elf-pthread-embedded circular dependencies not allowed
> -> mips64r5900el-ps2-elf-gccmips64r5900el-ps2-elf-pthread-embedded circular dependencies not allowed
> -> could not find all required packages: mpfr =4.2.0.p9

> yay -S  mpfr-static
> -> No AUR package found for mpfr=4.2.0.p9
> -> could not find all required packages: mpfr =4.2.0.p9

so from what I undestand the mpfr-static package is broken and if you are not the one that maintain these packages please just disregard this issue

**Comment by fjtrujy** [comment]
I don't know who is maintaining this package, but, for sure, we aren't.

Thanks
