### ISSUE TITLE
USBHDFSD - potential cache coherency bug when adding/renaming files

### ISSUE THREAD

**Issue by sp193** [ps2dev/ps2sdk#70]
USBHDFSD has a sector cache, which covers the whole disk in units of 4096-byte blocks. This is aligned with the start of the disk and has no relationship with any filesystem on the disk.

As such, if the code allocates a block before writing without reading the old content, it is perhaps possible for the remainder of the block to become lost.

For example:
| CLUSTER 1 | CLUSTER 2|...
..|  BLK1  | BLK2 | BLK3 |....

Where CLUSTER 1 and CLUSTER 2 are logical clusters in a filesystem, while BLK1, BLK2 and BLK3 are the blocks within the cache. The clusters are larger (for example, 32KB each) than the blocks (4KB each). The blocks are not aligned with the clusters (perhaps because there is 1KB alignment).

The software decides to allocate cluster 2, whose corresponding cache block contains some sectors that belongs to cluster 1. As the block is allocated and the old data being totally discarded, some of the sectors that belong to cluster 1 are lost.

The affected lines within fat_write.c concern direntry manipulation, so the user may observe corruption of FAT when:

- The cluster size is not a multiple of the block size. Or the clusters are not aligned with the blocks.
- Files or directories are added or renamed.
- The cluster that the direntry being updated exists in the middle of a cache block, which is shared with the adjacent cluster.

Line 1274: https://github.com/ps2dev/ps2sdk/blob/master/iop/usb/usbhdfsd/src/fat_write.c#L1274
Line 1308: https://github.com/ps2dev/ps2sdk/blob/master/iop/usb/usbhdfsd/src/fat_write.c#L1308

Personally, I have made a similar mistake before in 2014, which occasionally resulted in corruption when data is written: https://github.com/ps2dev/ps2sdk/commit/a9494c2dc8efa9430b17f05f9891b56194229c53#diff-ba7f9373100b558565bd2d05edac0ee8
So I do think it is a plausible design flaw within the FAT driver.

I shall make a branch and offer a prototype, for more individuals to test with.

EDIT:
Custom USBHDFSD module that does not use scache_allocSector in fat_write.c: https://www.sendspace.com/file/blz5os
Branch: https://github.com/sp193/ps2sdk/tree/usbhdfsd-scache-noalloc

One can test whether it is an improvement, by copying usbhdfsd-noscachealloc.irx as USBHDFSD.IRX, and to get LaunchELF to use it.

**Comment by Jay-Jay-OPL** [comment]
Yesterday I started a [topic discussing this issue ](http://www.ps2-home.com/forum/viewtopic.php?f=16&t=5848) with USB Flash Drives tending to get corrupted rather frequently after I upgraded from FMCB 1.94 to 1.96+

So I look forward in testing these prototypes.

**Question**?  Should we start to advise users to not upgrade to FMCB v1.96* or the current JUNE updates of wLE?

Is this issue with FMCB?  Or wLE or both combined?  I guess that's my question??? 

I'm also thinking that the reason why FMCB 1.94 doesn't have these issues, because all the current PS2SDK updates don't affect that version, since it was built a while back with an older PS2SDK build.

Did FMCB v1.95* have these issues also?  This way if we advise users to roll back, which of the two is the lesser of two evils. :-)

**Comment by sp193** [comment]
I have updated the first post to contain a link to my branch and to a prototype. This is not an actual fix for scache's shortcomings, but prevents the problem by reading the block before it is written (instead of just writing).

***

This problem is not with FMCB, but USBHDFSD. FMCB bundles the USBD and USBHDFSD modules, but they are not actually embedded within FMCB. These modules are stored as:
mc:/SYS-CONF/USBD.IRX
mc:/SYS-CONF/USBHDFSD.IRX
hdd0:/__sysconf/FMCB/USBD.IRX
hdd0:/__sysconf/FMCB/USBHDFSD.IRX

Only LaunchELF has a copy of these modules embedded, but you can get it to use external versions.

If this bug does actually exist, then there is no bug-free version of USBHDFSD because this bug was already there since day 1.

**Comment by rickgaiser** [comment]
Are we sure this issue is not related to the recent large-block read/write support? Or a combination of reading/writing large blocks and the scache?

I've been trying all sorts of things to get my usb stick corrupted but everything seems fine. I think in order to fix a problem we first must be able to reproduce it.

@Jay-Jay-OPL have you been able to reproduce this issue?

There's two other fat32 drivers in ps2sdk now that could possibly have the same issue: IEEE1394_disk and bdmfs_vfat. I don't think IEEE1394_disk is used anywhere, so should it be removed? For bdmfs_vfat I'm working on removing the scache, then introduce a new block device cache in bdm.

**Comment by sp193** [comment]
I have made this a part of the SDK, as well as part of FMCB v1.963 and LaunchELF. So that it becomes easier to know if it did help in any way. And if it does, then it would solve at least part of the problem.
Even if it does not actually work in the way I think it does, the change should be harmless.

I hope to keep this thread open, so that we can continue discussing the existence glitch here. Or in the best case, we reach a conclusion soon.

**Comment by Jay-Jay-OPL** [comment]
I think it's still failing.  See my most recent report here: [Reply #9](http://www.ps2-home.com/forum/viewtopic.php?p=29320#p29320)

FYI: the OPL ELF that I am referring to there is the one you provided for us to test for the ARP Table: https://github.com/ifcaro/Open-PS2-Loader/pull/101#issuecomment-402277656

**Comment by sp193** [comment]
In case it had something to do with the OHCI controller bug, I shortened the transfer length for writing to 4096 and noticed that the problem was getting worse.
So I inspected the scache_flushSectors() function and found a missing line. So hopefully, this other issue will be fixed as of commit 9772287.

Thank you for bringing this up.

**Comment by gingerbeardman** [comment]
I did a bunch some copying, renaming last night and did not encounter any errors. But good to see another bug squashed

**Comment by gingerbeardman** [comment]
Today I got some corruption, so I think it's not totally solved.

**Comment by Jay-Jay-OPL** [comment]
@sp193, this update works good with FTP'ing from PC to Mass, I can't seem to make it fail anymore. :)

But I give a full report here in this thread about another situation that happened before updating that may be another issue that we can look into: [Reply #11](http://www.ps2-home.com/forum/viewtopic.php?p=29372#p29372)

**Comment by sp193** [comment]
It is great, that it seems to have died down. Even with 1-2 cases, it may not be the same problem anymore.

@gingerbeardman: What exactly did you do? There are currently many possible reasons for things to go wrong.

What I have fixed, was a cause of corruption which caused corruption nearly every time data is written. Regardless of whether it's a new file or not. The earlier patch (mentioned at the start of this thread) was for a potential case of corruption, which could happen while writing new files or renaming.

What tool did you use to check the disk? I noted that using fsck from Linux may give a warning about the free space summary being wrong, and that is likely true (USBHDFSD does not update such a thing). But I don't think it is an actual cause for concern because it is just a summary and the Microsoft chkdsk tool does not deem that as a problem (no mention of such a summary either).

@Jay-Jay-OPL: LaunchELF will not write anything, unless you tell it to. This is a very simple piece of software, in terms of functionality for the user anyway.
You wrote before that you have two flash disks. Which one did this happen to? If you have been using only them, can you check if it ever happens to the other as well? Perhaps you can just start using it on a regular basis, just to see if it ever gives a different result.

If it really happened when you did not write anything, I think we cannot (yet) eliminate the possibility that there is a hardware incompatibility. It would mean that it was always there, since we cannot change the hardware.
We already have one infamous case, with Kingston devices.

**Comment by TnA-Plastic** [comment]
I noticed that some corruptions are more likely to re-appear, once the FS/Stick got corrupted (even if it got repaired via i.e. Chkdsk).

I think it is worth trying it with a 'fresh' and newly formatted drive!

**Comment by gingerbeardman** [comment]
I will check with a new drive, and record exact steps I am doing. 

But generally they are:

- copying BIOS (using "copy + rename" wLF feature)
- copying CHEATS.TXT and/or PATCHX.BIN into folders 
- editing CHEATS.TXT using wLF
- playing PS1 game with OPL (generates new directory containing 2x VMC memory card files)

I use
- Diskeeper (for realtime defrag in Windows)
- WinContig (defrag files that are written outside of Windows by PS2/Mac)

**Comment by sp193** [comment]
The problem here is that you used OPL. Unless you somehow got a new build that has the fixed driver, then it might corrupt the disk when you create the VMC files.

**Comment by TnA-Plastic** [comment]
These builds with the buggy driver even corrupt the disc, if USB is just started and some of the OPL-Specific folders are missing (thus it tries to create those folders and during that process corrupts some files)! ;)

I had that happen to me recently, but fortunately it doesn't happen in the newest builds.


By 'playing PS1 game with OPL' he probably means, that he has POPStarter set up the 'ps2home.com'-way... So he essentially starts a PS1-Game from the OPL-Daily Builds GUI, which starts POPStarter, which then starts the chosen game. ;)

**Comment by gingerbeardman** [comment]
>The problem here is that you used OPL. Unless you somehow got a new build that has the fixed driver, then it might corrupt the disk when you create the VMC files. ...

@sp193 ah! Yes. POPStarter through OPL.
 
@Jay-Jay-OPL are you aware of this?

**Comment by Jay-Jay-OPL** [comment]
I retired the old flash drive that I've used for years (PNY 32GB) -- meaning I don't use it anymore for PS2 Homebrew -- but that old sucker is still working fine loading other things on my other audio/video devices.

I then purchased two SanDisks (64GB / 32GB), I've been using the 64GB version for all the recent tests.

I plan to format it (SanDisk 64GB), to see if I can replicate that odd issue that just by browsing the folders within uLE could cause that folder/files to get corrupted.  If not, I guess we can say we are out of the woods for now.

Still testing the FTP issue, and no problems, it is working fine.  So at least that seems to be fixed (for now)...

**Comment by TnA-Plastic** [comment]
I don't want to spam this thread but I have to say it... 'for now' indeed is the appropriate wording/description!

**Comment by gingerbeardman** [comment]
@Jay-Jay-OPL what I meant is are you aware that the drivers inside OPL need updating? Would you do that or would you wait for it to be done upstream?

**Comment by gingerbeardman** [comment]
@sp193 will OPL get the fixed drivers soon?

**Comment by gingerbeardman** [comment]
In that case I will do some more testing.

**Comment by Jay-Jay-OPL** [comment]
@sp193, I haven't had much time testing more if USB HDD corruption has ceased to exist, since it's Summer and I usually have house guests -- one of disadvantages of living near paradise (i.e. a hot vacation spot).

But I wanted to also test a bug that was also reported a long time ago.  You see, for the longest I stayed back with FMCB 1.94 -- but I recall that users that started to use FMCB 1.95 would report a bizarre issue where if they tried to copy back and forth a file that had no extension and was 0 KB in size, that it would cause either USB HDD corruptions or uLE would refuse to transfer the file.

Do you recall such bug being mentioned in the past?  That is something I also would like to test also, but like I said, kind of difficult during this Summer time for me.  Hopefully you or someone else can test that?  If not, I will have to get back to you when I give that a good test.

**Comment by sp193** [comment]
Perhaps I was too eager to see this solved. We can keep this thread open longer, no problem!

From what I can see, the fs_read() and fs_write() functions prevent reading or writing of a 0-length file.
But for now, please try not to do anything weird like that. Even if you do successfully trigger the glitch, you will contaminate the results for the tests that we have been talking about within this thread. None of the fixes that have been brought up, would have addressed such an issue

**Comment by TnA-Plastic** [comment]
Would that prevention be a possible cause, if the GUI/backend of wLE doesn't realize it being not allowed?

**Comment by sp193** [comment]
I think it's just another issue, perhaps somewhere else. Unrelated to this thread. It may not even be within the SDK.
For starters, we have neither established what the symptoms are like nor what the conditions for triggering the bug are. If it can be replicated, please open a new issue ticket.

**Comment by gingerbeardman** [comment]
So I have recently been chasing an issue which turned out to be a corrupt save game due to POPS.

And I realised it's POPS that creates the save folders and VMC files, not OPL.

So I think it's enough to put the IRX next to POPS [as detailed in its wiki](https://bitbucket.org/ShaolinAssassin/popstarter-documentation-stuff/wiki/irx-loader)?
Or does this means that (discontinued) POPS needs to be modified to include the fixed USB drivers?

**Comment by Jay-Jay-OPL** [comment]
@sp193, okay, I finally had time to test this some more... (no more house guests, yay!)  

Please go here and read my latest update in [Reply #13](http://www.ps2-home.com/forum/viewtopic.php?p=29986#p29986)

**Comment by sp193** [comment]
@gingerbeardman Yes, its USB modules have to be updated as well. Thankfully, it has a function to use externally-supplied USB modules.
You can refer to this post: http://www.psx-place.com/threads/popstarter-external-hdd-error.19326/#post-131008

@Jay-Jay-OPL Thanks for taking the time to check it out.
I don't really know why you can destroy folders just by accessing them. It's just impossible, through normal means.
What do you usually do before accessing the folder? Is there any chance that you last experienced an incomplete write, before reseting the PS2 and accessing this affected folder?

But what do you mean by "the file that was transferred was not 100% complete"? Was the copied file incomplete/different in any way (and in what way?), or did you mean that LaunchELF gets stuck while copying the file?
If the file was incomplete/different, I would appreciate it if you could describe the corruption. Like at what offset it occurs at and how long the bad regions are, and whether the pattern repeats across the file.

There was one more mistake that I found, related to the workaround for unaligned writes. However, that is likely not applicable to LaunchELF, although the alignment of the buffers utilized by LaunchELF is insufficient to not require software correction. It's at least aligned to 16-byte addresses.
I cannot really say it will not happen for the FTP server, however.

As for what we can try now:
Today's build (control): https://www.sendspace.com/file/05j4ef
With write transfers limited to 4KB (the original limitation of older drivers): https://www.sendspace.com/file/wbcp8g

If bottom file somehow magically solves the problem with files occasionally being incompletely written, then perhaps the hardware is just incompatible with at least some devices.

**Comment by gingerbeardman** [comment]
Interestingly, I've moved from a _SanDisk Cruzer Fit USB 2.0_ to _SanDisk Ultra Flair USB 3.0_ (mainly for faster writes from my PC) and have not seen any corruptions (though I also pre-generated all my game folders and blank VMC through a batch file)

I will also try the POPS USB drivers.

**Comment by gingerbeardman** [comment]
OK, this is worrying. 

Copy from USB to USB using only uLaunchELF corrupts file, leaving lots of holes of zero bytes inside it.

original file: [POPSTARTER.OG.ELF.zip](https://github.com/ps2dev/ps2sdk/files/2220881/POPSTARTER.OG.ELF.zip)
copied file: 
[POPSTARTER.ELF.zip](https://github.com/ps2dev/ps2sdk/files/2220883/POPSTARTER.ELF.zip)

At this point, I cannot trust any file I copied using wLE — which is a lot! Probably all my save games :cry:

**Comment by gingerbeardman** [comment]
I've prepared a pack of control files, filled only with `0xFF` and ranging in size from 1KB through to 1024KB. Feel free to use them to check file copy/writing functions.

[FF.zip](https://github.com/ps2dev/ps2sdk/files/2221437/FF.zip)

When I tried to copy these control files to another folder from their folder, their own folder became corrupted after only two files had been copied. So could this problem be a fragmentation issue?

I could recover the contents using `chkdsk /F`.

**Comment by sp193** [comment]
Are you using the latest version, especially after the bug in cache-writeback was found (4th July)? It has to be at least that version.

The logic between reading and writing seems quite similar. How strange.
The holes seem to be of some irregular lengths too (not a multiple of 512), Although they begin at some aligned address.

I would blame the cache, but the holes seem to be very strange in length.

Can you try the 2 files I provided above? In case either the new glitch that was fixed (with regards to unaligned accesses) was relevant or if there is some relationship with how we increased the maximum transfer length.

**Comment by gingerbeardman** [comment]
I'll try the other builds. 

I deleted my previous message about the holes in a moment of sleep-deprived madness. If you have the ability or the contents, please reinstate it. Apologies!

**Comment by gingerbeardman** [comment]
Just a thought, there is already the MD5 hash check code in ps2sdk: https://github.com/ps2dev/ps2sdk/blob/master/common/tcpip/lwip-2.0.0/src/netif/ppp/polarssl/md5.c

So is it possible to have a build that checks MD5 after copy? Or on demand through a context menu item? Would be very useful because I would not have to roundtrip to my computer to check validity of files.

**Comment by sp193** [comment]
You must understand that the part that deals with the USB device is the USB Mass Storage device driver, USBHDFSD. Not the app you run.
But since each PS2 app has control over the PS2, each one will likely have their own modules. And so the only way to change USBHDFSD is to change the app.

The version of FMCB you use, hence _does not actually matter_. Other than the fact that other software may use its modules (but there is no formal arrangement for this) and FMCB bundles some version of LaunchELF (which you can also replace) that carries its own USB modules. This is why I have been handing out versions of LaunchELF for tests, but not FMCB.

The old modules that come with old versions of LaunchELF are not faultless either, but you likely just never encountered their problems. For example, the mistake I mentioned at the beginning of this thread was there since day 1 and I have probably seen it corrupt my disks before (although it was quite uncommon).
They're also incapable of creating directories properly and have less error-handling for USB device stalls (hence why our PS2s used to hang more often at boot). These are some reasons why we must move on.

Now we're trying to lift the transfer length limitation of USBHDFSD, which was there since the dawn of time. This is the part that seems problematic. It seems to read properly (you cannot boot ELFs or read JPEGs properly without being able to read properly) and the code for writing is similar, so the logic for writing should be fine. You also seem to always get corruption (even when it's supposed to be impossible), so I cannot rule out a hardware compatibility problem.

For v1.964, I also updated the USB modules and LaunchELF. Since a mistake was found, I decided to ship out the patch as soon as possible.
There were no real changes between v1.963 and v1.964, other than external files (USB modules, HDDLOAD and LaunchELF) and the version number (hence the minor increment).

**Comment by sp193** [comment]
From the file you provided, it looks like a single, 4KB region of corruption that is on a boundary that is nicely aligned for the cache system (+0x108000). Within the region has an ELF header.
It might be related to the cache, but I haven't seen anything unusual though.

**Comment by Jay-Jay-OPL** [comment]
When I formatted the flash drive, I allowed the FAT32 app to auto select the cluster size.

So it was:  32768 bytes (32K)

I guess it selected that cluster size, since the flash drive is under 64GB in size.

**Comment by gingerbeardman** [comment]
mine is also 32kb.

**Comment by gingerbeardman** [comment]
I am back to testing this.

My method is to use [HashCheck](https://github.com/gurnec/HashCheck/releases) to generate a checksum file containing MD5 of all items on the USB drive. Then do some file manipulation and generate a second checksum file. Comparing will show me which files were modified outside of my control, then I can inspect the disk to see if they were adjacent in storage.

**Comment by gingerbeardman** [comment]
OK, I have reformatted by USB drive and loaded on a fresh set of files, calculated checksums and I am ready to cause some destruction. Hahaha.

**Comment by sp193** [comment]
If anybody uses this special version of LaunchELF with PLANETTY, it should become possible to tell what is being written and how the device responds. However, this doesn't mean we'll surely find something, unfortunately.

I have not tested this. But I know the PC clients work.

To anyone who participates in this experiment, thank you.

----
@gingerbeardman Thank you for trying to help though. I didn't have an actual way to gather some information, but now there may be some way.

----

Instructions:
1. Copy BOOT-USBTEST.ELF to a place where you can launch it on the PlayStation 2.
2. Copy planetty/planetty.exe to your PC.
3. Run BOOT-USBTEST.ELF on the PlayStation 2.
4. Start planetty, specifying the IP address of the PlayStation 2. Redirect the output to a file, for easy submission.
	For example, if your PS2 is at 192.168.0.182:
```		planetty 192.168.0.182 > result.log```
5. Access the USB device normally. Attempt to trigger the bug. Log messages will be sent over the network to your PC.
7. Break the output of planetty with CTRL+C, when done.

LaunchELF will use your IP configuration in mc:/SYS-CONF/IPCONFIG.DAT.
If you have issues with getting planetty to capture log messages from the PlayStation 2, you may need to disable your firewall (e.g. Windows Firewall).

| File	 | Description |
|------|----------------|
| BOOT-USBTEST.ELF | Test program for the PlayStation 2 console |
| planetty | Terminal client for Linux |
| planetty.exe | Terminal client for Windows |
| src (in other archive) | Source code for the tools |

Binaries: https://www.sendspace.com/file/jgxnhv
Source code: https://www.sendspace.com/file/1uqywo

**Comment by Badore90** [comment]
This program, planetty.exe doesn't work with my pc (Windows 10 - 64-bit)

**Comment by sp193** [comment]
Can you elaborate on the problem? This does work on Windows 7 x64.
If you are missing a DLL, you probably have to install the Microsoft Visual C++ 2010 Redistributable package (x86).

**Comment by gingerbeardman** [comment]
I'll try this soon

**Comment by sp193** [comment]
You need to run it from the command prompt. If you need some help with using the command prompt:

- Extract the .7z archive to C:\test
- Run the command prompt.
- Type cd C:\test
- Type planetty 192.168.0.182 > results.log
- Press CTRL+C to terminate the logging, when done. results.txt will contain the logged messages.

Replace the 192.168.0.182 with your PlayStation 2's IP address.

**Comment by Badore90** [comment]
![wp_20181024_19_50_28_pro](https://user-images.githubusercontent.com/44087144/47453484-20998680-d7cd-11e8-87af-2ce764157191.jpg)

It keeps giving me problems… The program must start even when I'm not connected to the Ps2 right??

**Comment by gingerbeardman** [comment]
@sp193 you have no PS2!? Amazing. 

I'll test this today.

**Comment by Badore90** [comment]
yes of course 
![immagine](https://user-images.githubusercontent.com/44087144/47501650-4b83e900-d866-11e8-8f49-27cc49a6a95f.jpg)

I'll ask you the question again: "The program must start even when I'm not connected to the Ps2 right??"
Mybe the program doesn't work when i'm not connected to the Ps2??  excuse the ignorance...

**Comment by sp193** [comment]
No, it does not matter. Can you use the command prompt (cmd) instead? I don't know if using the Powershell makes a difference.

**Comment by Badore90** [comment]
I thought Windows 10 just changes the command prompt name in PowerShell. 
Contrariwise there also the command prompt. I'll try with it

**Comment by Badore90** [comment]
Ok it works, thank you. I'll test it with the ps2 as soon as I can 

P.S. sorry but I'm quite ignorant in Ps2 SMB. Therefore if there's something else I must know to make it work (like to activate some sharing permissions in the test folder, etc…), let me know. So that I can go without failon the next try :)

**Comment by sp193** [comment]
We're not using SMB, so no worries. I'm more concerned if this can actually allow us to capture such a bug, which doesn't usually occur. Or if it doesn't even work as intended, since I never tested it.

**Comment by Badore90** [comment]
Here the file [results.log](https://github.com/ps2dev/ps2sdk/files/2516121/results.log)
I copied BOOT.ELF (that is OPL_DB_1330) from MC1 to mass (Toshiba usbHDD 500gb), the copy process seems to end without problems as always. Then I launch the just copied file and got a black screen.

I after repeated the exactly same process with Ule 4.42d and the copied elf works flawlessy.

**Comment by Badore90** [comment]
the log's lenght depends from the file's size?? 'Cause if it's a problem I can repeat the process copying a smaller file (like Ule)

**Comment by sp193** [comment]
Yes, the more data copied, the longer it will be. I thought we were going to try and see why we sometimes get "paste failed" though.
If you want to try to fix this other "unsolvable" problem of USBHDFSD writing files incorrectly, you need to dump your HDD and to give me a file comparison. Otherwise, I cannot tell why and where it's going wrong.

**Comment by sp193** [comment]
Tell you what. I think there is one thing I didn't consider, which is sectorSkip. I'll spend some time thinking about it, before making further updates if/when necessary. And in the meantime, other people can help with scrutinizing the code.

I haven't figured out why it seems to read fine if not considering sectorSkip while computing the number of consecutive sectors is wrong, but it might be wrong because it could be considering the wrong indexes for sectors between clusters.

**Comment by Badore90** [comment]
I can repeat the test with an empty pen-drive, ok?? 

It would be possible to add the communication with planetty to Ule 4.42d?? In order to make a comparison

About the "paste failed" I can't remembrer if it never happened to me. The paste failed, but the program isn't aware of it, no error messages.

**Comment by sp193** [comment]
I think it may be easier for you (and other people) to try using this build of LaunchELF instead: https://www.sendspace.com/file/ojtkg6

If it is a problem with USBHDFSD, then it is not really a LaunchELF problem. Also because too much time has passed between 2011 and 2018, there has been a number of other changes made to USBHDFSD. So with the changes in behaviour to USBHDFSD and the likelihood of USBHDFSD selecting the same clusters on the disk to copy files to, it will be very difficult to do a simple comparison of logs...

I am pretty convinced that without considering sectorSkip (the number of leading sectors to skip within the  first cluster before reading/writing) is a problem.
With this new build of LaunchELF, I attempted to view JPEG and PNG images and there was problem with doing that. I tried to duplicate JPEG and PNG on the disk to another directory, and they were transferred with no issues. I also copied RDB from my memory card to USB disk, and it seems fine.
chkdsk reported no corruption, but my USB disk now has very few files on it.

Please let me know if the new commit helps, so I can quickly push it to ps2dev/ps2sdk, so as to limit the spread of the defective USBHDFSD module.

**Comment by gingerbeardman** [comment]
I'll try soon, promise. 

Aside: where there ever any attempts to utilise existing OSS projects to provide FAT support? [FatFs](http://elm-chan.org/fsw/ff/00index_e.html), [Petit FS](http://elm-chan.org/fsw/ff/00index_p.html)

**Comment by sp193** [comment]
I need to attend to other things, so I have committed the change and made new releases for all the software that I have jurisdiction over. 
I'm going to hope that I actually fixed the problem. If not, I will be sad. But that will be in a few days. haha

Either way, thank you all for helping me with solving the issues that were introduced since June 8th, as well as the handful of 11-year old bugs.

No, I don't know if anybody did port homebrew FAT libraries for this purpose. It is possible that it was just not done because the module in question, USBHDFSD, was created a really long time ago (2007?) under a different name (usbmass).
We're also constrained by the resources that the PS2 has. So it is also a good idea to keep the modules as simple as possible. Sometimes, writing a new module is the best way, despite all the obstacles and effort needed. Needlessly to say, developing software for this console is just challenging.

However, I know that the ps2netbox guy did port a library for exFAT support. I don't know the details though.
He was interested in keeping things closed-source because he wanted to sell a complete product.
But, I am not sure whether it's even legal because Microsoft says "A license is required in order to implement exFAT and use it in a product or device."

**Comment by Badore90** [comment]
Tried BOOT-181027.ELF ...I don't know, what modifications have you made??
It perfectly copied the files (I tried also OPL_DB_1330 that gave me black screen the other day), all ELFs starts correctly.
...But, then I tried with your builds from your previous links (and with ule 4.43 from fmcb 1964 too) and they all perfectly copied the files now.

I wonder if therefore it's a random thing or maybe it's a modules question?? In the last case it possible that after booting your last build the others too start to work??

I don't have any idea how these things work, I'm saying that from my experience playing games from internal HDD. There are some games that required to load the HDD modules once from Ule (or FMCB configurator) and then they work with OPL (at least until you made some modifications, etc...).

**Comment by Badore90** [comment]
Tried with another Ps2 and the pasted ELF always works, I can copy/paste it with any build.
So unless your last build made some modifications to my USB-HDD modules (or the way the Ps2 recognize it, I don't know…) it's a random thing.

Btw it's a little weird, 'cause though I didn't made many, all my pasted files was bad until I tried your last build, it would be a crazy coincidence.

**Comment by Badore90** [comment]
I'll try with another Ps2 and another USB device tomorrow

**Comment by sp193** [comment]
[This commit](https://github.com/ps2dev/ps2sdk/commit/4333a06eeb4d81eedecade715e7ef5a2b892e590) is the relevant commit. Yes, I changed only the USBHDFSD module, which provides access to USB Mass Storage Devices.

It is precisely because the bug depends on what is on your disk (and hence what the bug can destroy) and the cluster size, that we all get varying results.

Please destroy all old versions of software made between June 8th and September 26th, when you can. Since they contain bugged versions of USBHDFSD, then they are only good for destroying data.

All standard PlayStation 2 software have full control over the PS2, and are hence responsible for loading the modules that they require. Only some devices, like the CD/DVD drive and ROM will have the necessary modules loaded by default. Other devices like the memory card and HDD unit, require additional modules to be loaded. USB mass storage devices and the USB OHCI controller are also included.

If you're thinking of that case where booting "supported" software before booting any newer software would allow those "GameStar" adaptors to somehow become compatible, it is working around the hardware bug in those adaptors by initializing the bad adaptor first, hence avoiding the incompatible initialization code of the newer modules.

Either way, thank you. And all other participants.

**Comment by Badore90** [comment]
> If you're thinking of that case where booting "supported" software before booting any newer software would allow those "GameStar" adaptors to somehow become compatible, it is working around the hardware bug in those adaptors by initializing the bad adaptor first, hence avoiding the incompatible initialization code of the newer modules.

Well I done this too. When formatting my 2tb HDD with the gamestar NA: loaded modules with Ule 4.42d, then Ule 4.43a 2tb edition could see it.

However I I wanted to say something else. i.e. the game Ferrari challenge trofeo pirelli.
You can see here: http://www.psx-place.com/threads/open-ps2-loader-game-bug-reports.19401/  the tenth game in the list
or here: http://psx-scene.com/forums/f150/open-ps2-loader-game-compatibility-62463/index53.html  at the post #529

This game is given to not work (it freeze at the second loading time)

But actually there are 2 ways to make this game work (with any HDL/OPL version)

1. You can just launch HDL/OPL from a usb device
2. (this is the werid one to which I referred) you can make this game work even booting HDL/OPL (any version) from your MC. 
You must first load the HDD with a FMCB program (Ule or FMCB installer), doesn't matter wich version or wich NA you're using and doesn't matter even if the modules are loaded or not, just to try is enough (like with Ule 4.43a with a Gamestar NA, it try to load the modules a couple of time, then leave the HDD turned-off, but is is enough to make the game not freezing).

This way the game won't freeze even using HDL/OPL(any version) from the MC. You can reset you Ps2 all times you want, the game now will ever work… until you leave your Ps2 turned off from the main power for a long time, or if you make certain modifications to your HDD (like installing(deleting a game) or in your MC. 
I can't be more precise about what modifications affect it. Anyway if at some point the game return to freeze, you can just repeat the FMCB load (or try to load) modules process.

One of the latest OPL daily builds, seems to solved this though. I think from DB_1330. With it there's no more need to do this process, the game never freeze.

**Comment by sp193** [comment]
I see. Anyway, thank you and the others for helping out.
I shall be closing this issue. It was long derailed from the original problem, although the other issues were somewhat still related.

You may all feel free to bring it up again, if you have substantial facts to revisit the issues that USBHDFSD may still have.
