### ISSUE TITLE
Heap allocation functions - are they really thread-safe as documented?

### ISSUE THREAD

**Issue by sp193** [ps2dev/ps2sdk#75]
Hi all,

For a really long time, I have been asking myself this question: are the heap allocation functions (AllocSysMemory and FreeSysMemory) thread-safe?

As of the Sony SDK v3.0.2, the documentation for AllocSysMemory states that it is multi-thread safe, does not depend on whether interrupts are disabled or enabled. However, it was documented to not support being called from the interrupt context.

But from disassembling these functions myself and referring to the code from the FPS2BIOS project, it appears that the AllocSysMemory and FreeSysMemory functions have no inter-task protection. This design seemed to be the same, from the old SDK 1.3.4 release (i.e. our boot ROM's version of SYSMEM) to the one from IOPRP310 (SDK 3.1.0).

The Sony developers didn't seem to all agree with each other too. Some of them just called AllocSysMemory() and FreeSysMemory() without suspending interrupts, while some others suspend interrupts before calling these functions.
Early versions of USBD do not suspend interrupts before calling these functions, but interrupts are first suspended in later versions.
In the HDD modules (HDD.IRX and PFS.IRX), interrupts were always suspended before calling these functions.
In modules like FILEIO, AllocSysMemory is always called without suspending interrupts.

I've long forgotten if I ever got any issues from using these functions without suspending interrupts, but I have been suspending interrupts in my code before I use any of them.

**Comment by rickgaiser** [comment]
I guess this depends on another descussion about how threads work on the IOP:
- threads can only be interrupted by interrupts
- interrupt handlers cannot call these functions

So we only need to worry about thread safety if another thread starts as a result from an interrupt while inside AllocSysMemory() or FreeSysMemory(). And there's been some discussion about whether this is possible or not.

Can an interrupt return to a higher priority thread? If so then these functions need to be thread safe, or called with interrupts disabled.

Why don't we make a simple test .irx, with 2 threads:
- thread1: low priority, runs forever in a loop, calling AllocSysMemory() and FreeSysMemory()
- thread2: high priority, triggered periodically with an interrupt, calling AllocSysMemory() and FreeSysMemory() once, then going back to sleep

If interrupts cannot return to a higher priority thread, then the IOP will be stuck inside thread1 (but I don't think this is the case).

If interrupts do return to the higher priority thread, then calling any thread-unsafe function will cause problems. Probably a memory leak, or crash.

**Comment by uyjulian** [comment]
The code for suspending/resuming interrupts in `AllocSysMemory` and `FreeSysMemory` was added at some point between 1.3.4 and 3.1.0. Pointers to `CpuSuspendIntr` and `CpuResumeIntr` are passed to `loadcore` and `sysmem` internal structures from `modload`.

So, it is only thread safe if using the new modules.

So, basically:
* When using old modules, wrap the call between `CpuSuspendIntr` and `CpuResumeIntr`
* When using new modules, and you do not need compatibility with the old modules, you do not need to wrap the call
