### ISSUE TITLE
Q. -DF_ idiom

### ISSUE THREAD

**Issue by uucidl** [ps2dev/ps2sdk#77]
The makefiles in ps2sdk use a curious idiom I hadn't seen before, which I will call the -DF_ idiom

So apparently there are `.c` files from which many `.o` files get produced. 

The c files are organized as so:

lib.c:
```C
/* <bunch of stuff>*/
#ifdef F_Foo
int Foo(Arg1, Arg2)
{
}
#endif

#ifdef F_Bar
int Bar(Arg1, Arg2)
{
}
#endif
```

Then the makefiles are structured so that:

Makefile
```Make
LIB_OBJS=Foo.o Bar.o

$(LIB_OBJS:%=$(EE_OBJS_DIR)%): $(EE_SRC_DIR)lib.c
	$(EE_C_COMPILE) -DF_$(*:$(EE_OBJS_DIR)%=%) $< -c -o $@
```

Effectively this means that `n` calls to the compiler will be made:
```sh
cc -DF_Foo -c -o Output/Foo.o
cc -DF_Bar -c -o Output/Bar.o
```

Now that I described the setup..  What is the purpose of that idiom? It comes from way back and I
don't see an explanation there about what it accomplishes.

Was it originally introduced to allow compiling lib.c with -DF_Foo and -DF_Bar as one or as separate objs if one wishes to? Was it to control exactly which symbols get compiled?

**Comment by sp193** [comment]
This structure allows us to break up a file that contains multiple functions (and shared data) into smaller objects. Usually, only one function is placed in each object, within the built library.
This would cause GCC to only select and link with the necessary functions, rather than the whole library.

**Comment by uucidl** [comment]
It's interesting, so this is a way to perform dead-code elimination!

For those finding this issue later on: 

https://elinux.org/images/2/2d/ELC2010-gc-sections_Denys_Vlasenko.pdf

Here is a presentation that explains how the linker is indeed .o based, and provides some other alternative using gcc.

**Comment by uucidl** [comment]
(And thanks for the answer)
