### ISSUE TITLE
Handling interface selection within USBHDFSD correctly

### ISSUE THREAD

**Issue by sp193** [ps2dev/ps2sdk#79]
As of commit d443c152 on June 8th, some devices have become incompatible with USBHDFSD due to usb_set_interface becoming a mandatory step. This also implies that the Set Interface step never succeeds on some devices. Rolling back is the easy way out, but it seems like calling Set Interface was not even the correct thing to do in the first place.

By following the Linux source code, the USB Mass Storage class specification and the USB 2.0 specification (The related clauses should be similar), I have arrived at these conclusions:
- By 9.4.10 of the USB 2.0 spec, a device may STALL if only one configuration is supported.
- By 9.6.5 of the USB 2.0 spec and 4.3 of the USB Mass Storage class spec documents, a device may implement multiple interfaces, of which there may be multiple alternate configurations. Alternate interface 0 is the default. The driver is supposed to iterate through all interface descriptors and pick the best fit.
- There was nothing that stated that the bulk-only data interface (used for the USB Mass Storage class) will be the first in a composite device.
- If the device stalls the pipe when Set Interface is done, then Linux will issue CLEAR HALT on the pipes of the alternate interface.
- By the USB Mass Storage class spec, there seems to not be a case where there will be alternate interfaces, so we can avoid calling Set Interface entirely. Linux does not seem to use Set Interface on USB Mass Storage devices.

Since USBHDFSD does not actually scan through all interface descriptors, it does not actually support composite devices. The only composite devices that will work with this, will be those that have the bulk-only data interface as the first interface.

So I see that we have two choices:
- Complete support for composite devices. This means adding code that will scan through all the interface descriptors. Select the appropriate interface during the connect() step.
- Officially drop support for composite devices. Assume that only USB Mass Storage devices will be used, whereby they only have one interface.

As I have no composite devices, I plan to just cut off the broken support for them.
Also in case I am wrong about any of the points I have gathered so far, I have opened this issue ticket for discussion.

**Comment by sp193** [comment]
I changed my mind. I think I'll just implement the Linux workaround of clearing the HALT state on the pipes and call it a day. Removal of the Set Interface step can be done later, or not at all. I still cannot tell for sure, what is the right thing to do about it. As of now, USBHDFSD has no code for scanning for the most suitable alternate interface setting either.

The fix to this issue is in commit d27752e.

On a side note, section 3.3 of the USB Mass Storage Class CBI specification 1.1 states that only the data interface of composite mass storage devices is enabled when the default configuration is selected. This allows minimal control of mass storage devices by software with limited capabilities, such as BIOS. Hence it is permissible for USBHDFSD to not scan through all interface descriptors, but simply selecting the first interface descriptor is okay (as how it is done now).

I'll keep this issue open for a few more days, in case anybody has further comments.

**Comment by PGAnonamous** [comment]
@sp193 I think you mistakenly used the wrong usb release in iop/usb/usbmass_bd/src/usb_mass.c You used mass_stor_release(dev); instead of usb_mass_release(dev);

**Comment by Jay-Jay-OPL** [comment]
Just one question.  Does this new change affect OPL?  If yes, should we compile the current version of OPL again, to test these new changes?  And should we do the same for wLE?

**Comment by sp193** [comment]
Yes, since both have USB support. However, the change has not been propagated to OPL's in-game code yet, since I have not decided if the changes within this commit will be all that is necessary for totally solving this design issue. Although it will probably stay this way.
