### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by hgdagon** [ps2dev/ps2sdk#80]
I get this message right after `libkernel` is built:

```
make[2]: Leaving directory '/run/media/hgdagon/Gateway/ps2toolchain/build/ps2sdk/ee/libc'
make[2]: Leaving directory '/run/media/hgdagon/Gateway/ps2toolchain/build/ps2sdk/ee/kernel'
make[2]: Leaving directory '/run/media/hgdagon/Gateway/ps2toolchain/build/ps2sdk/ee/kernel-nopatch'
make[1]: Leaving directory '/run/media/hgdagon/Gateway/ps2toolchain/build/ps2sdk/ee'
make: *** [Makefile:31: all-ee] Error 2
../scripts/005-ps2sdk.sh: Failed.
ERROR: Could not run the toolchain script.
```

The problem is I don't even know what failed. I'm running latest Manjaro.

**Comment by uyjulian** [comment]
Post the full log on https://gist.github.com/ and post the link here

**Comment by hgdagon** [comment]
Full log. Do I need to run the whole thing again?

**Comment by hgdagon** [comment]
https://gist.github.com/hgdagon/638088224ac3372f0ad06a1845493faf

**Comment by uyjulian** [comment]
Multi-job building is broken. Don't use `-j`  
If you are using ps2toolchain, on line 31 of `scripts/005-ps2sdk.sh` change `make -j $PROC_NR` to `make` for now.  
I'm working on a proper fix.

**Comment by hgdagon** [comment]
Worked. I was going around looking at line 31's of all makefiles...

**Comment by sp193** [comment]
The -j option was already removed. If you haven't updated ps2toolchain over the past 48 hours, please update it.

**Comment by uyjulian** [comment]
The `-j` option was not entirely removed. `-j` with no arguments means to use all cores. From the GNU make manpage:

>      -j [jobs], --jobs[=jobs]
>            Specifies the number of jobs (commands) to run simultaneously.  If
>            there  is  more than one -j option, the last one is effective.  If
>            the -j option is given without an argument, make  will  not  limit
>            the number of jobs that can run simultaneously.

**Comment by sp193** [comment]
I see. :(
Okay, I have replaced the defective commit. Thank you for the update.

**Comment by uyjulian** [comment]
No problem.
